import React from "react";
import "./footer.css";
import logoweb from '../assets/logoweb.png';
var Footer = function () {
    return (React.createElement(React.Fragment, null,
        React.createElement("footer", null,
            React.createElement("div", { className: 'container' },
                React.createElement("div", { className: 'box bigest' },
                    React.createElement("div", { className: 'logo' },
                        React.createElement("img", { src: logoweb, alt: '', style: { maxWidth: '70%' } }),
                        React.createElement("h2", null, "Do You Need Help With Anything?"),
                        React.createElement("p", null, "Receive updates, hot deals, discounts sent straight to your inbox every month"),
                        React.createElement("div", { className: 'input flex' },
                            React.createElement("input", { type: 'text', placeholder: 'Email Address' }),
                            React.createElement("button", { style: { marginLeft: '20px', backgroundColor: '#E00947' } }, "Subscribe")))),
                React.createElement("div", { className: 'responsive-box' },
                    React.createElement("div", { style: { marginLeft: '100px', width: '200px' }, className: 'box' },
                        React.createElement("center", null,
                            " ",
                            React.createElement("h3", null, "Follow Us"),
                            React.createElement("ul", null,
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: 'https://web.facebook.com/login/?_rdc=1&_rdr' }, "Facebook")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: 'https://www.whatsapp.com/download' }, "Whatsapp ")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: 'https://www.instagram.com/accounts/login/?hl=en' }, "Instergram ")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: 'https://web.botim.me/#/' }, "Botim")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: 'https://web.telegram.org/k/' }, "Teligram ")))),
                        " ")),
                React.createElement("div", { className: 'responsive-box' },
                    React.createElement("div", { style: { marginLeft: '100px', width: '200px' }, className: 'box' },
                        React.createElement("center", null,
                            "   ",
                            React.createElement("h3", null, "Company"),
                            React.createElement("ul", null,
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: '/aboutus' }, "About us ")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: '/contactus' }, "Contact us ")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: '/join' }, "Join with Us ")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: '/details' }, "Details")),
                                React.createElement("li", null,
                                    "  ",
                                    React.createElement("a", { style: { color: 'white' }, href: '/chat' }, "chat ")))),
                        " ")),
                React.createElement("div", { className: 'res' },
                    React.createElement("div", { style: { marginLeft: '100px', width: '200px' }, className: 'box' },
                        React.createElement("center", null,
                            " ",
                            React.createElement("h3", null, "App"),
                            React.createElement("ul", null,
                                React.createElement("li", null,
                                    React.createElement("a", { href: 'https://play.google.com/store/games?hl=en&gl=US&pli=1' },
                                        React.createElement("img", { src: 'https://freelogopng.com/images/all_img/1664287128google-play-store-logo-png.png', alt: '', style: { width: '130px' } }))),
                                React.createElement("li", null,
                                    React.createElement("a", { href: 'https://www.apple.com/app-store/' },
                                        React.createElement("img", { src: 'https://w7.pngwing.com/pngs/34/523/png-transparent-app-store-apple-logo-apple-text-logo-video-game.png', alt: '', style: { width: '130px' } }),
                                        "  ")))),
                        "  ")))),
        React.createElement("div", { className: 'legal' },
            React.createElement("span", null, "\u00A9 2024 . Eventleadership Institute."))));
};
export default Footer;
