import React from 'react';
import UserNavigation from '../Navigations/userNav';
import '../CSS/contentCreaterPage.css';
import Contentimge1 from '../assets/contentpgstudent1.jpg';
import Contentimge2 from '../assets/contendpgstudent2.jpg';
import slidimd1 from '../assets/slidimg1.jpeg';
import slidimd2 from '../assets/slidimg2.jpg';
import slidimd3 from '../assets/slidimg3.jpg';
import 'bootstrap/dist/css/bootstrap.min.css';
import { Link } from 'react-router-dom';
import Advertisment from '../page/classpost';
export default function ContentCreatorPage() {
    return (React.createElement("div", null,
        React.createElement(UserNavigation, null),
        React.createElement("div", { className: "app" },
            React.createElement("style", null, ".blog-container {\n      display: flex;\n      justify-content: space-between;\n      padding: 20px;\n    }\n    \n    .video-section {\n      flex: 1;\n      margin-right: 20px;\n    }\n    \n    .youtube-video {\n      width: 100%;\n      height: 100%;\n      aspect-ratio: 16/9;\n    }\n    \n    .description-section {\n      flex: 1;\n    }\n    \n    .description-section h2 {\n      margin-top: 50px;\n      margin-bottom: 30px; \n      font-size: 32px;\n      font-weight: bold;\n    }\n    \n    .description-section p {\n      font-size: 16px;\n      line-height: 1.5;\n    }\n\n    "),
            React.createElement("div", { className: "heropageconten " },
                React.createElement("div", { className: "bigtitle m-6" },
                    React.createElement("h1", { className: "bigtitle m-6", "data-aos": "fade-left" }, "The best program to Enroll for exchange"),
                    React.createElement(Link, { to: '#' },
                        " ",
                        React.createElement("button", { className: "btn btn-outline-warning" }, "Find INSTRUCTORS \u2192"))),
                React.createElement("div", { className: 'heroimg' },
                    React.createElement("div", { className: "intro-images2", "data-aos": "fade-up", "data-aos-duration": "3000" },
                        React.createElement("img", { src: Contentimge2, alt: "hero banner" })),
                    React.createElement("div", { className: "intro-images", "data-aos": "fade-left", "data-aos-anchor": "#example-anchor", "data-aos-offset": "500", "data-aos-duration": "5000" },
                        React.createElement("img", { src: Contentimge1, alt: "hero banner" })))),
            React.createElement(Advertisment, null),
            React.createElement("section", { className: "features" },
                React.createElement("div", { className: "feature1", "data-aos": "zoom-in" },
                    React.createElement("h2", null, "QUALIFIED INSTRUCTORS"),
                    React.createElement("p", null, "We have the best knowledge & thought leaders in many fields of study willing to share what they know.")),
                React.createElement("div", { className: "feature2", "data-aos": "zoom-in" },
                    React.createElement("h2", null, "THOUSANDS OF STUDENTS"),
                    React.createElement("p", null, "The only platform in Sri Lanka, connecting thousands of students with the best tutors in the industry.")),
                React.createElement("div", { className: "feature3", "data-aos": "zoom-in" },
                    React.createElement("h2", null, "100+ COURSES TO SELECT FROM"),
                    React.createElement("p", null, "Largest selection of courses with strict quality control. Best place to learn online in Sri Lanka."))),
            React.createElement("section", { className: "instructors" },
                React.createElement("div", { className: "allinstructorsimgandword" },
                    React.createElement("div", { className: "instructor-card " },
                        React.createElement("img", { src: Contentimge2, alt: "hero banner" })),
                    React.createElement("div", { className: "instructorcwords" },
                        React.createElement("h2", null, "INSTRUCTORS"),
                        React.createElement("h3", null, "Ray Sanchez"),
                        React.createElement("p", null, "Minim veniam nostrud exer citation."),
                        React.createElement("p", null, "20K+ Enrolled learners"),
                        React.createElement(Link, { to: '/SSABS/user/userhome/FindINSTRUCTORS' },
                            " ",
                            React.createElement("button", { className: "btn btn-outline-warning" }, "Find INSTRUCTORS \u2192"))))),
            React.createElement("div", { className: "slidimgs" },
                React.createElement("div", { className: "description" },
                    React.createElement("p", null, "Shrimp farming, a subset of aquaculture, has emerged as a lucrative and sustainable method for meeting the increasing global demand for shrimp. This practice involves the breeding, raising, and harvesting of shrimp in controlled environments, such as tanks or ponds. Technological advancements have significantly enhanced the efficiency and yield of shrimp farms, making it a profitable venture for many entrepreneurs and businesses.")),
                React.createElement("div", { id: "carouselExampleAutoplaying", className: "carousel slide", "data-bs-ride": "carousel" },
                    React.createElement("div", { className: "carousel-inner" },
                        React.createElement("div", { className: "carousel-item active" },
                            React.createElement("img", { src: slidimd1, className: "d-block w-100", alt: "First slide" })),
                        React.createElement("div", { className: "carousel-item" },
                            React.createElement("img", { src: slidimd2, className: "d-block w-100", alt: "Second slide" })),
                        React.createElement("div", { className: "carousel-item" },
                            React.createElement("img", { src: slidimd3, className: "d-block w-100", alt: "Third slide" }))),
                    React.createElement("button", { className: "carousel-control-prev", type: "button", "data-bs-target": "#carouselExampleAutoplaying", "data-bs-slide": "prev" },
                        React.createElement("span", { className: "carousel-control-prev-icon", "aria-hidden": "true" }),
                        React.createElement("span", { className: "visually-hidden" }, "Previous")),
                    React.createElement("button", { className: "carousel-control-next", type: "button", "data-bs-target": "#carouselExampleAutoplaying", "data-bs-slide": "next" },
                        React.createElement("span", { className: "carousel-control-next-icon", "aria-hidden": "true" }),
                        React.createElement("span", { className: "visually-hidden" }, "Next")))),
            React.createElement("section", { className: "courses" },
                React.createElement("h2", { className: 'catagorypoost' }, "categories to explore when learning about shrimp"),
                React.createElement("div", { className: "course-list" },
                    React.createElement("div", { className: "course-card" },
                        React.createElement("h3", { className: 'topicwordscard' }, "Aquaculture and Farming Techniques:"),
                        React.createElement("p", { className: 'dipwordpost' }, "Explore the various methods and technologies used in shrimp farming, such as pond culture, recirculating aquaculture systems (RAS), and biofloc technology.")),
                    React.createElement("div", { className: "course-card" },
                        React.createElement("h3", { className: 'topicwordscard' }, "Shrimp Species and Biology:"),
                        React.createElement("p", { className: 'dipwordpost' }, "Study the different species of shrimp commonly farmed around the world, such as Pacific white shrimp (Litopenaeus vannamei), black tiger shrimp (Penaeus monodon), and freshwater prawns (Macrobrachium spp.).")),
                    React.createElement("div", { className: "course-card" },
                        React.createElement("h3", { className: 'topicwordscard' }, "Market Trends and Economics:"),
                        React.createElement("p", { className: 'dipwordpost' }, "Investigate global trends in shrimp consumption, production, and trade, including key importing and exporting countries. Analyze market dynamics, pricing factors, and demand drivers influencing the shrimp industry, such as consumer preferences, dietary trends, and health considerations.")))),
            React.createElement("div", { className: "blog-container" },
                React.createElement("div", { className: "video-section" },
                    React.createElement("iframe", { className: "youtube-video", src: "https://www.youtube.com/embed/1AK_RQ1uaGs", frameBorder: "0", allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture", allowFullScreen: true, title: "YouTube Video" })),
                React.createElement("div", { className: "description-section" },
                    React.createElement("h2", null, "LOREM IPSUM"),
                    React.createElement("p", null, "America's largest indoor shrimp farm operates with cutting-edge aquaculture technology to produce and sell around 2 million shrimp annually. Utilizing a controlled environment, the farm ensures optimal conditions for shrimp growth, free from the challenges of traditional outdoor farming such as disease, weather fluctuations, and pollutants.                 "),
                    React.createElement("p", null, "This indoor setup includes advanced water filtration systems, precise temperature control, and sustainable practices to maximize shrimp health and yield. The farm's commitment to quality and sustainability has positioned it as a leader in the industry, meeting the growing demand for fresh, locally-sourced shrimp.                "))))));
}
